### ISSUE TITLE
Create CLI to send Kafka messages that can be used in different components

### ISSUE THREAD

**Issue by pacospace** [thoth-station/messaging#167]
As Thoth component,

 I want to produce message to send to Kafka using CLI in thoth-messaging.

**Additional context**
See conversation https://github.com/thoth-station/solver/issues/579#issuecomment-659239758

**Comment by KPostOffice** [comment]
Do we want to be able to send multiple messages with the CLI or just one?

**Comment by pacospace** [comment]
> Do we want to be able to send multiple messages with the CLI or just one?

I think multiple messages might be useful, for example for graph-refresh-job, we want to run the cronjob and send messages for:
- `UnresolvedPackageMessage` (to send messages to schedule solver), 
- `UnrevsolvedPackageMessage` (to send messages to schedule revsolver)
- `UnanalyzedSecurityPackageMessage` (to send messages to schedule security).
- etc..

@fridex WDYT?

**Comment by pacospace** [comment]
> > Do we want to be able to send multiple messages with the CLI or just one?
> 
> I think multiple messages might be useful, for example for graph-refresh-job, we want to run the cronjob and send messages for:
> 
> * `UnresolvedPackageMessage` (to send messages to schedule solver),
> * `UnrevsolvedPackageMessage` (to send messages to schedule revsolver)
> * `UnanalyzedSecurityPackageMessage` (to send messages to schedule security-analyzer).
> * etc..
> 
> @fridex WDYT?

I didn't see conversation here: https://github.com/thoth-station/solver/issues/579#issuecomment-660442425, what about graph-refresh-job? Should become a CronWorkflow with different steps querying the database?

**Comment by fridex** [comment]
> > Do we want to be able to send multiple messages with the CLI or just one?
> 
> I think multiple messages might be useful, for example for graph-refresh-job, we want to run the cronjob and send messages for:
> 
> * `UnresolvedPackageMessage` (to send messages to schedule solver),
> * `UnrevsolvedPackageMessage` (to send messages to schedule revsolver)
> * `UnanalyzedSecurityPackageMessage` (to send messages to schedule security-analyzer).
> * etc..
> 

I think this is the logic we want to have in the investigator. The message `UnresolvedPackageMessage` says we have a package to solve and investigator decides what should be done. If the package was already solved by a different solver, there is no need to run reverse solver. If the package is a new release we don't know, we need to run reverse solver.

The security indicator workflow is run similarly based on new/already analyzed package. (But the condition/logic when to run what can be different in investigator based on the knowledge we have and type of message investigator receives).

The purpose of messaging CLI is one simple taks - send a message based on CLI parameters/env vars. This can be then incorporated into argo workflows we will have - when to send what message.

**Comment by fridex** [comment]
> > > Do we want to be able to send multiple messages with the CLI or just one?
> > 
> > 
> > I think multiple messages might be useful, for example for graph-refresh-job, we want to run the cronjob and send messages for:
> > 
> > * `UnresolvedPackageMessage` (to send messages to schedule solver),
> > * `UnrevsolvedPackageMessage` (to send messages to schedule revsolver)
> > * `UnanalyzedSecurityPackageMessage` (to send messages to schedule security-analyzer).
> > * etc..
> > 
> > @fridex WDYT?
> 
> I didn't see conversation here: [thoth-station/solver#579 (comment)](https://github.com/thoth-station/solver/issues/579#issuecomment-660442425), what about graph-refresh-job? Should become a CronWorkflow with different steps querying the database?

I think we can keep it as is for now until we implement investigator. After that, we can change it so it sends messages instead of directly using `schedule_*` methods from `OpenShift`. We can turn it to CronWorkflow to easily integrate Argo metrics, and have a unified system (kubernetes/openshift objects will then become lower level objects and the application will be made out workflows solely to be extensible).

**Comment by pacospace** [comment]
> > > Do we want to be able to send multiple messages with the CLI or just one?
> > 
> > 
> > I think multiple messages might be useful, for example for graph-refresh-job, we want to run the cronjob and send messages for:
> > 
> > * `UnresolvedPackageMessage` (to send messages to schedule solver),
> > * `UnrevsolvedPackageMessage` (to send messages to schedule revsolver)
> > * `UnanalyzedSecurityPackageMessage` (to send messages to schedule security-analyzer).
> > * etc..
> 
> I think this is the logic we want to have in the investigator. The message `UnresolvedPackageMessage` says we have a package to solve and investigator decides what should be done. If the package was already solved by a different solver, there is no need to run reverse solver. If the package is a new release we don't know, we need to run reverse solver.
> 
> The security indicator workflow is run similarly based on new/already analyzed package. (But the condition/logic when to run what can be different in investigator based on the knowledge we have and type of message investigator receives).
> 
> The purpose of messaging CLI is one simple taks - send a message based on CLI parameters/env vars. This can be then incorporated into argo workflows we will have - when to send what message.



> > > Do we want to be able to send multiple messages with the CLI or just one?
> > 
> > 
> > I think multiple messages might be useful, for example for graph-refresh-job, we want to run the cronjob and send messages for:
> > 
> > * `UnresolvedPackageMessage` (to send messages to schedule solver),
> > * `UnrevsolvedPackageMessage` (to send messages to schedule revsolver)
> > * `UnanalyzedSecurityPackageMessage` (to send messages to schedule security-analyzer).
> > * etc..
> 
> I think this is the logic we want to have in the investigator. The message `UnresolvedPackageMessage` says we have a package to solve and investigator decides what should be done. If the package was already solved by a different solver, there is no need to run reverse solver. If the package is a new release we don't know, we need to run reverse solver.
> 
> The security indicator workflow is run similarly based on new/already analyzed package. (But the condition/logic when to run what can be different in investigator based on the knowledge we have and type of message investigator receives).
> 
> The purpose of messaging CLI is one simple taks - send a message based on CLI parameters/env vars. This can be then incorporated into argo workflows we will have - when to send what message.

Sounds good, thanks!

**Comment by pacospace** [comment]
> > > > Do we want to be able to send multiple messages with the CLI or just one?
> > > 
> > > 
> > > I think multiple messages might be useful, for example for graph-refresh-job, we want to run the cronjob and send messages for:
> > > 
> > > * `UnresolvedPackageMessage` (to send messages to schedule solver),
> > > * `UnrevsolvedPackageMessage` (to send messages to schedule revsolver)
> > > * `UnanalyzedSecurityPackageMessage` (to send messages to schedule security-analyzer).
> > > * etc..
> > 
> > 
> > I think this is the logic we want to have in the investigator. The message `UnresolvedPackageMessage` says we have a package to solve and investigator decides what should be done. If the package was already solved by a different solver, there is no need to run reverse solver. If the package is a new release we don't know, we need to run reverse solver.
> > The security indicator workflow is run similarly based on new/already analyzed package. (But the condition/logic when to run what can be different in investigator based on the knowledge we have and type of message investigator receives).
> > The purpose of messaging CLI is one simple taks - send a message based on CLI parameters/env vars. This can be then incorporated into argo workflows we will have - when to send what message.
> 
> > > > Do we want to be able to send multiple messages with the CLI or just one?
> > > 
> > > 
> > > I think multiple messages might be useful, for example for graph-refresh-job, we want to run the cronjob and send messages for:
> > > 
> > > * `UnresolvedPackageMessage` (to send messages to schedule solver),
> > > * `UnrevsolvedPackageMessage` (to send messages to schedule revsolver)
> > > * `UnanalyzedSecurityPackageMessage` (to send messages to schedule security-analyzer).
> > > * etc..
> > 
> > 
> > I think this is the logic we want to have in the investigator. The message `UnresolvedPackageMessage` says we have a package to solve and investigator decides what should be done. If the package was already solved by a different solver, there is no need to run reverse solver. If the package is a new release we don't know, we need to run reverse solver.
> > The security indicator workflow is run similarly based on new/already analyzed package. (But the condition/logic when to run what can be different in investigator based on the knowledge we have and type of message investigator receives).
> > The purpose of messaging CLI is one simple taks - send a message based on CLI parameters/env vars. This can be then incorporated into argo workflows we will have - when to send what message.
> 
> Sounds good, thanks!

What about different components sending UnresolvePackageMessage? Do we want to have a parameter in the message to known which component is sending the message? Because we might want to do differentiate depending on which component is sending the message. 

What about the logic of producer currently present in investigator for adviser? Where do we migrate that? thoth-messaging? or new workflow task in workflow-helpers?

**Comment by fridex** [comment]
> * What about the logic of producer currently present in investigator for adviser? Where do we migrate that? thoth-messaging? or new workflow task in workflow-helpers?

Which part are you referring to? Could you point me to sources?

**Comment by pacospace** [comment]
> > * What about the logic of producer currently present in investigator for adviser? Where do we migrate that? thoth-messaging? or new workflow task in workflow-helpers?
> 
> Which part are you referring to? Could you point me to sources?

https://github.com/thoth-station/investigator/blob/master/producer.py

**Comment by fridex** [comment]
> > > * What about the logic of producer currently present in investigator for adviser? Where do we migrate that? thoth-messaging? or new workflow task in workflow-helpers?
> > 
> > 
> > Which part are you referring to? Could you point me to sources?
> 
> * https://github.com/thoth-station/investigator/blob/69d3a3ecdd0d495843ff2acea369ea98f0a393ce/producer.py#L47
> * https://github.com/thoth-station/thoth-application/blob/ec5c8445aaf200c82ad9b776cad0770512ddf3f4/adviser/base/argo-workflows/investigate-unresolved-package.yaml#L17

Yes, they can eventually end up in the messaging module.

**Comment by goern** [comment]
I like this thread, nice work all!

**Comment by KPostOffice** [comment]
https://github.com/thoth-station/messaging/pull/170

**Comment by pacospace** [comment]
> > > > Do we want to be able to send multiple messages with the CLI or just one?
> > > 
> > > 
> > > I think multiple messages might be useful, for example for graph-refresh-job, we want to run the cronjob and send messages for:
> > > 
> > > * `UnresolvedPackageMessage` (to send messages to schedule solver),
> > > * `UnrevsolvedPackageMessage` (to send messages to schedule revsolver)
> > > * `UnanalyzedSecurityPackageMessage` (to send messages to schedule security-analyzer).
> > > * etc..
> > > 
> > > @fridex WDYT?
> > 
> > 
> > I didn't see conversation here: [thoth-station/solver#579 (comment)](https://github.com/thoth-station/solver/issues/579#issuecomment-660442425), what about graph-refresh-job? Should become a CronWorkflow with different steps querying the database?
> 
> I think we can keep it as is for now until we implement investigator. After that, we can change it so it sends messages instead of directly using `schedule_*` methods from `OpenShift`. We can turn it to CronWorkflow to easily integrate Argo metrics, and have a unified system (kubernetes/openshift objects will then become lower level objects and the application will be made out workflows solely to be extensible).

After talking to @KPostOffice realized graph refresh job can be archived if we move the logic it is using to package update producer, WDYT? @KPostOffice @fridex @Goern. 

Package update will need to check database for unresolved packages as graph refresh from any solver and send UnresolvedPackageMessage basically, then investigator will take care of the rest with the current logic.

**Comment by fridex** [comment]
> > > > > Do we want to be able to send multiple messages with the CLI or just one?
> > > > 
> > > > 
> > > > I think multiple messages might be useful, for example for graph-refresh-job, we want to run the cronjob and send messages for:
> > > > 
> > > > * `UnresolvedPackageMessage` (to send messages to schedule solver),
> > > > * `UnrevsolvedPackageMessage` (to send messages to schedule revsolver)
> > > > * `UnanalyzedSecurityPackageMessage` (to send messages to schedule security-analyzer).
> > > > * etc..
> > > > 
> > > > @fridex WDYT?
> > > 
> > > 
> > > I didn't see conversation here: [thoth-station/solver#579 (comment)](https://github.com/thoth-station/solver/issues/579#issuecomment-660442425), what about graph-refresh-job? Should become a CronWorkflow with different steps querying the database?
> > 
> > 
> > I think we can keep it as is for now until we implement investigator. After that, we can change it so it sends messages instead of directly using `schedule_*` methods from `OpenShift`. We can turn it to CronWorkflow to easily integrate Argo metrics, and have a unified system (kubernetes/openshift objects will then become lower level objects and the application will be made out workflows solely to be extensible).
> 
> After talking to @KPostOffice realized graph refresh job can be archived if we move the logic it is using to package update producer, WDYT? @KPostOffice @fridex @goern.
> 
> Package update will need to check database for unresolved packages as graph refresh from any solver and send UnresolvedPackageMessage basically, then investigator will take care of the rest with the current logic.
> 
> So we can maintain only one component.

I think splitting logic to multiple components to let each do one task and do it well is the way to go long term. The package update job is responsible for checking available packages on indexes registered in Thoth - if there is something wrong OpenShift/Kubernetes/Argo can handle errors for this task. The goal of graph refresh job is to check what backages need to be solved as part of reconciliation - check packages that we haven't solved yet because of new solvers installed, new packages comming from container image analyses and such. I don't see reason why we would merge these two components. We have bots that assist us to manage repositories and keep components in sync. If we put all the logic to one place we will not create scalable and extensible solutions.

**Comment by pacospace** [comment]
> > > > > > Do we want to be able to send multiple messages with the CLI or just one?
> > > > > 
> > > > > 
> > > > > I think multiple messages might be useful, for example for graph-refresh-job, we want to run the cronjob and send messages for:
> > > > > 
> > > > > * `UnresolvedPackageMessage` (to send messages to schedule solver),
> > > > > * `UnrevsolvedPackageMessage` (to send messages to schedule revsolver)
> > > > > * `UnanalyzedSecurityPackageMessage` (to send messages to schedule security-analyzer).
> > > > > * etc..
> > > > > 
> > > > > @fridex WDYT?
> > > > 
> > > > 
> > > > I didn't see conversation here: [thoth-station/solver#579 (comment)](https://github.com/thoth-station/solver/issues/579#issuecomment-660442425), what about graph-refresh-job? Should become a CronWorkflow with different steps querying the database?
> > > 
> > > 
> > > I think we can keep it as is for now until we implement investigator. After that, we can change it so it sends messages instead of directly using `schedule_*` methods from `OpenShift`. We can turn it to CronWorkflow to easily integrate Argo metrics, and have a unified system (kubernetes/openshift objects will then become lower level objects and the application will be made out workflows solely to be extensible).
> > 
> > 
> > After talking to @KPostOffice realized graph refresh job can be archived if we move the logic it is using to package update producer, WDYT? @KPostOffice @fridex @goern.
> > Package update will need to check database for unresolved packages as graph refresh from any solver and send UnresolvedPackageMessage basically, then investigator will take care of the rest with the current logic.
> > So we can maintain only one component.
> 
> I think splitting logic to multiple components to let each do one task and do it well is the way to go long term. The package update job is responsible for checking available packages on indexes registered in Thoth - if there is something wrong OpenShift/Kubernetes/Argo can handle errors for this task. The goal of graph refresh job is to check what backages need to be solved as part of reconciliation - check packages that we haven't solved yet because of new solvers installed, new packages comming from container image analyses and such. I don't see reason why we would merge these two components. We have bots that assist us to manage repositories and keep components in sync. If we put all the logic to one place we will not create scalable and extensible solutions.

Thanks for all clarification and explanation!

**Comment by pacospace** [comment]
And this issue has been solved by: https://github.com/thoth-station/messaging/pull/170. We can close it :)
