### ISSUE TITLE
Add component_name and service_version  to each message

### ISSUE THREAD

**Issue by pacospace** [thoth-station/messaging#216]
**Is your feature request related to a problem? Please describe.**
Different components in Thoth send same message, we need to have a way to 

**Describe the solution you'd like**
Add parameters to each message.

**Describe alternatives you've considered**

**Additional context**
@fridex

**Comment by KPostOffice** [comment]
Why do we need to know which component sent the message?

**Comment by fridex** [comment]
> Why do we need to know which component sent the message?

It can help with traceability as the application becomes more complex. We already have different message producers that produce the same message -- it can help to trace what happened in the system. Also, consumers could act differently based on the producer in some (rare?) cases.

**Comment by KPostOffice** [comment]
@fridex 
I don't love the idea of handling the messages differently based on component. I think if they should be handled differently they should be different messages, but in terms of traceability that makes sense :+1:

**Comment by pacospace** [comment]
Fixed by https://github.com/thoth-station/messaging/pull/224
