### ISSUE TITLE
Adding persistant memory to our Faust App (RocksDB) [? add points]

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/messaging#225]
Using the memory:// store is OK when developing your project and testing things out, but for large tables, it can take hours to recover after a restart, so you should never use it in production.
RocksDB recovers tables in seconds or less, is embedded and don’t require a server or additional infrastructure. It also stores table data on the file system in such a way that tables can exceed the size of available memory.

With everything being moved to Kafka it becomes important make sure we don't lose messages. As @KPostOffice suggested we could add a PVC that prevents us from losing messages in case the pod goes down, 

Ref - https://faust.readthedocs.io/en/latest/userguide/application.html#id2

**Comment by KPostOffice** [comment]
This no longer applies due to confluent-kafka
