### ISSUE TITLE
Message versioning update

### ISSUE THREAD

**Issue by KPostOffice** [thoth-station/messaging#287]
**Is your feature request related to a problem? Please describe.**
Add message versioning to message contents so that we have a more clear way of updating when message contents change.

**Describe the solution you'd like**
1. Message contents and version change
2. Add a new handler to message handler lookup table in investigator
3. Update producer to use message type
4. If we come across a message which we cannot handle we block the agent and send an alarm

*\**steps 2 and 3 should be able to happen in either order

**Steps to complete**
- [ ] add `message_version` to base message contents and send when producing message
- [ ] Add handler lookup table to `investigator`
- [ ] Add alert when message does not have a handler for that version

**Comment by pacospace** [comment]
Solved by @KPostOffice
