### ISSUE TITLE
Lock down producer messaging versions

### ISSUE THREAD

**Issue by KPostOffice** [thoth-station/messaging#302]
**Describe the issue**
Lock down all message producers to release directly before confluent rework.  Faust producers will work even if consumer has moved to confluent.  We can then switch over without worrying about breaking changes occuring.

**ToDo:**
- [x] Package update
- [x] Package releases
- [x] Investigator producer (this one should be done at the same time as investigator)
- [x] Advise reporter
- [x] graph refresh

**Comment by pacospace** [comment]
> **Describe the issue**
> Lock down all message producers to release directly before confluent rework. Faust producers will work even if consumer has moved to confluent. We can then switch over without worrying about breaking changes occuring.
> 
> **ToDo:**
> 
> * [ ]  Package update
> * [ ]  Package releases
> * [ ]  Investigator producer (this one should be done at the same time as investigator)

I'm removing investigator producer and create a task that store messages to be sent in workflow helpers: https://github.com/orgs/thoth-station/projects/14#card-42363021
> * [ ]  Advise reporter
> * [ ]  graph refresh

**Comment by KPostOffice** [comment]
`thoth-messaging==0.7.13`

**Comment by pacospace** [comment]
All components have been lockded, we can close the issues
