### ISSUE TITLE
Versioned message contents are not strict

### ISSUE THREAD

**Issue by KPostOffice** [thoth-station/messaging#350]
**Is your feature request related to a problem? Please describe.**
In message contents, we have lines such as this:
```
runtime_environment = attr.ib(type=Optional[Dict[Any, Any]], default=None)
```
this allows for some arbitrary dictionary to be passed as a runtime environment in the message. If the definition of a `runtime_environment` changes, this is not reflected in the message version.

It might be the case that versioning messages cannot have *strict* guarantees as to the message contents, instead we may just want to strive for strict forward compatibility of message schemas. Only ever adding to schemas to make them more permissive and create these definitions as something that we can inherit across thoth modules.

**Describe the solution you'd like**
I would like to be able to use strict definitions to construct my messages so that we can validate the entire contents of the message.

This would require creating jsonschema definitions in other thoth-modules.

**Describe alternatives you've considered**
We can leave the definition as is and allow these contents of messages to be **very** permissive as to what constitutes a "runtime_environment".  This approach allows for a simpler dev flow as we do not have to worry about schemas, however, if someone decides that they want to pass `{False: True, "foo": "baz"}` as the contents of `runtime_environment` there is nothing stopping them.

I am not sure how much we care about validating objects within a message. Please let me know what you think.

**Comment by fridex** [comment]
Validation of `runtime_environment` is done:

* client-side (which does not enforce it's validity on the backend):

https://github.com/thoth-station/thamos/blob/fe589f2b304063b8dc091ea1dd6b844c35abc438/thamos/config.py#L60

* user-api:

https://github.com/thoth-station/user-api/blob/c90d53874c0b4c8ed334131754a604e53dec437a/openapi/openapi.yaml#L1591

* and in adviser which parses the runtime environment provided and issues warning if there is anything wrong with it (e.g. unknown entries):

https://github.com/thoth-station/common/blob/a40d96080ae929c512132900842c5dcb4380b97a/thoth/common/config/runtime_environment.py#L39

* see also this relevant discussion that is related to openapi models generated out of API:

https://github.com/thoth-station/thamos/pull/672#discussion_r561723222

With the jsonschema solution for messaging, I think the strict schema could be easily enforced on the messaging layer. I'm personally 50/50 for doing that.

**Comment by fridex** [comment]
> I'm personally 50/50 for doing that.

Maybe I'll be more explicit here. I see pros like strict message types, but on the other hand, it might cause issues with the overall system user experience. Having these messages strictly conforming to a schema might require specific versions of thamos on the client side which would couple user tooling and the backend service (user api) - users will need to make sure they use the right thamos when communicating with Thoth backend (update or downgrade which might require additional work). We can do so by sending a message from user-api "update your thamos" which could be good to notify users about some aspects anyway. The main question here is if we want to allow partially good `runtime_environment` entries being present in the system.

**Comment by KPostOffice** [comment]
@fridex What happens if backend is expecting some param that an old version of thamos doesn't provide?

**Comment by fridex** [comment]
> @fridex What happens if backend is expecting some param that an old version of thamos doesn't provide?

All the parameters in `runtime_environment` are optional.

**Comment by fridex** [comment]
I think we can slightly twist the issue here. Might be good to use strict types in pydantic: https://pydantic-docs.helpmanual.io/usage/types/#strict-types

/assign @KPostOffice 
/remove-lifecycle stale
