### ISSUE TITLE
init=False is missing in some of messages version parameter

### ISSUE THREAD

**Issue by pacospace** [thoth-station/messaging#353]
**Describe the bug**
Not sure if it is a bug, but better to have consistency. cc @harshad16 

**To Reproduce**
1. Have a look at `version` in some messages classes `init=False is missing in some of messages version parameter`

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by KPostOffice** [comment]
@pacospace This is no longer an issue. Can you close the issue please? :smile:
